server:
  port: 8080
spring:
  config:
    import: optional:secrets/application-secrets.yaml
  application:
    name: barbershop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.jdbc-url}/${database.schema}?useTimezone=true&serverTimezone=UTC
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  flyway:
    url: ${database.jdbc-url}
    schemas: ${database.schema}
    user: ${database.username}
    password: ${database.password}
  jackson:
    default-property-inclusion: use-defaults
    serialization:
      fail-on-empty-beans: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
logging:
  level:
    root: info
database:
  jdbc-url: ${jdbc_url}
  schema: ${db_schema}
  username: ${db_username}
  password: ${db_password}
