server:
  port: 8080
spring:
  config:
    import: optional:secrets.yaml
  application:
    name: barbershop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/barbershop?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  flyway:
    url: jdbc:mysql://localhost:3306/
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: barbershop
  jackson:
    default-property-inclusion: use-defaults
    serialization:
      fail-on-empty-beans: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
logging:
  level:
    root: info
