# This file is a template for your local environment configuration.

# 1. Create a new file:
# Create a new file named application-secrets.yaml in the same folder as this template file.
# This file will contain your local environment configuration and should not be committed to your Git repository.
#
# 2. Use this template as a guide:
# The properties in this template are set with dummy values and should not be used in your environment.
# Set the properties found in this template in your application-secrets.yaml file with real values.
#
# 3. Secure your configuration:
# Keep the application-secrets.yaml file secure and do not share it with anyone.
database:
  jdbc-url: jdbc:mysql://localhost:3306
  schema: database_name
  username: your_username
  password: your_password
